### ISSUE TITLE
Fix MacOS builds: OSError: dlopen(libusb-1.0.dylib, 6): image not found

### ISSUE THREAD

**Issue by maltfield** [BusKill/buskill-app#87]
This issue will track the effort to fix our currently-broken MacOS builds, which produce the following error when attempting to arm buskill

```
00:52:06,27 packages.buskill DEBUG DEBUG: Exception thrown in child process: Failed to load dynlib/dll 'libusb-1.0.dylib'. Most likely this dynlib/dll was not found when the application was frozen.

00:52:06,37 packages.buskill DEBUG DEBUG: Traceback: Traceback (most recent call last):
  File "PyInstaller/loader/pyimod03_ctypes.py", line 53, in __init__
  File "ctypes/__init__.py", line 379, in __init__
OSError: dlopen(libusb-1.0.dylib, 6): image not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "buskill/__init__.py", line 1632, in run
    multiprocessing.Process.run(self)
  File "multiprocessing/process.py", line 108, in run
  File "buskill/__init__.py", line 1104, in armNix
    with usb1.USBContext() as context:
  File "usb1/__init__.py", line 2144, in __enter__
  File "usb1/__init__.py", line 2174, in open
  File "usb1/_libusb1.py", line 210, in loadLibrary
  File "usb1/_libusb1.py", line 219, in __loadLibrary
  File "usb1/_libusb1.py", line 158, in __getLibrary
  File "PyInstaller/loader/pyimod03_ctypes.py", line 55, in __init__
pyimod03_ctypes.install.<locals>.PyInstallerImportError: Failed to load dynlib/dll 'libusb-1.0.dylib'. Most likely this dynlib/dll was not found when the application was frozen.
```

This issue was discovered when attempting to solve #77 
 * https://github.com/BusKill/buskill-app/issues/77

**Comment by maltfield** [comment]
Currently, the MacOS builds finish "successfully". And I'm able to download, "install", and execute the BusKill app.

I only get an error (now correctly captured by the GUI thanks to the [commits earlier today](https://github.com/BusKill/buskill-app/issues/77#issuecomment-2254234599) when clicking the "arm" button.

It appears that the `libusb-1.0.dylib` file is missing from the BusKill macOS app, which is needed for the non-root child process (referenced as `usb_handler`) to watch for usb hotplug events (whoose callback executes the trigger function).

The change that most-likely broke this was the software bumps done in #78

 * https://github.com/BusKill/buskill-app/issues/78

In ^ that ticket, we changed from `libusb-1.0.23.tar.bz2` to `libusb-1.0.27.tar.bz2`

**Comment by maltfield** [comment]
I thought that maybe all I needed to do was to update `1.0.23` to `1.0.27` in a few places in the build script (and, indeed, those were never updated), but I unfortunately also discovered that there is **no files named dylib** in the new tarball

```
user@buskill:/tmp/libusb-1.0.27$ find . | grep -i dylib
user@buskill:/tmp/libusb-1.0.27$ 
```

...so this might be more complicated than initially expected

**Comment by maltfield** [comment]
huh, I downloaded and extracted all the libusb releases from `1.0.23` until today, and none of them had any `dylib` files. I guess I got it from someplace else

```
user@disp187:~/Downloads/libusb$ ls
libusb-1.0.23              libusb-1.0.24.tar.bz2  libusb-1.0.26-rc1.tar.bz2  libusb-1.0.27-rc2
libusb-1.0.23.tar.bz2      libusb-1.0.25          libusb-1.0.26.tar.bz2      libusb-1.0.27-rc2.tar.bz2
libusb-1.0.24              libusb-1.0.25.tar.bz2  libusb-1.0.27              libusb-1.0.27.tar.bz2
libusb-1.0.24-rc1          libusb-1.0.26          libusb-1.0.27-rc1
libusb-1.0.24-rc1.tar.bz2  libusb-1.0.26-rc1      libusb-1.0.27-rc1.tar.bz2
user@disp187:~/Downloads/libusb$ 

user@disp187:~/Downloads/libusb$ find . | grep -i dylib
user@disp187:~/Downloads/libusb$
```

**Comment by maltfield** [comment]
oh, duh, the `dylib` file *doesn't* exist in the tarball. It gets created after we `make` it

https://github.com/BusKill/buskill-app/blob/53f631d7cf45bcafc752a520625099d0fcca9ede/build/mac/buildDmg.sh#L254-L263

**Comment by maltfield** [comment]
After ^ that change, the latest build now runs without throwing an error upon arming.

 * https://github.com/BusKill/buskill-app/releases/tag/10127516447_mac

This is fixed

**Comment by hexxone** [comment]
Thanks for your effort in getting this running on MacOs, unfortunately Its still not working for me.

<img width="301" height="328" alt="Image" src="https://github.com/user-attachments/assets/11725a24-db1a-40ec-8500-eac75799c155" />

Do you know what might be the problem here?

**Comment by maltfield** [comment]
fyi, I replied in #91 as your issue seems unrelated to *this* ticket
